In [1]:
import tensorflow as tf
import numpy as np

In [466]:
no_of_actions=4
state_dim=9

In [314]:
eps=1
gama=0.5

In [223]:
class KerasEnv:
    def __init__(self):
        self.env=tf.keras.Sequential()
        self.env.add(tf.keras.layers.Dense(state_dim+1,input_shape=(state_dim+1,),activation='sigmoid'))
        
    def get_observation(self,state,action):
        action=np.expand_dims(np.expand_dims(action, axis=0),axis=0)
        s=np.concatenate((state,action),axis=1)
        obs=self.env.predict(s)
        s=obs[0,0:obs.shape[1]-1].reshape(1,state_dim)
        r=obs[0,obs.shape[1]-1]
    
        return (s,r)
        
     
   


In [475]:
class Grid:
    def __init__(self):
        self.grid=np.array([[0,10,0],[10,100,10],[100,1000,100]])
        self.punishment=-1000
        
        
    def get_observation(self,state,action):
        x=state%3
        y=(int)(state/3)
        next_state=np.zeros((no_of_actions)).astype('int')
        reward=np.zeros((no_of_actions))
        
        
  
        if(x>0):
            next_state[0]=(x-1)+y*3  
            reward[0]=self.grid[x-1][y]
        
        else:
            next_state[0]=state
            reward[0]=self.punishment
        
        if(x<2):
            next_state[1]=(x+1)+y*3 
            reward[1]=self.grid[x+1][y]
        
        else:
            next_state[1]=state
            reward[1]=self.punishment
        
        if(y>0):
            next_state[2]=(x)+(y-1)*3  
            reward[2]=self.grid[x][y-1]
        
        else:
            next_state[2]=state
            reward[2]=self.punishment
        
        if(y<2):
            next_state[3]=(x)+(y+1)*3  
            reward[3]=self.grid[x][y+1]
        
        else:
            next_state[3]=state
            reward[3]=self.punishment
        
        
            
        return (next_state[action],reward)
    
def get_action(model,state):
    a=np.array(np.random.choice([np.argmax(model[state]),np.random.randint(4)],p=[eps,1-eps]))
    return a
        

In [476]:
state=0


env=Grid()
model=np.zeros((state_dim,no_of_actions))


for i in range(100):
    eps=i/100
    print(model)
    action=get_action(model,state)
    (next_state,reward)=env.get_observation(state,action)
    print(reward+np.max(model[next_state]))
    model[state]=reward+np.max(model[next_state])
    state=next_state
    
  

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[-1000.    10. -1000.    10.]
[[-1000.    10. -1000.    10.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]]
[-1000.    10. -1000.    10.]
[[-1000.    10. -1000.    10.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]]
[-1000.   100.     0.     0.]
[[-1000.    10. -1000.    10.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [-1000.   100.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0

In [482]:
state=6
count=0
for i in range(1000):
    
    action=get_action(model,state)
    (next_state,reward)=env.get_observation(state,action)
    print(state,next_state,action,reward)
    count=count+1
    if(reward[action]==1000):
        break
    state=next_state
    
print(count)

6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. -1000.]
6 6 0 [-1000.    10.    10. 

In [436]:
class Grid:
    def __init__(self):
        self.grid=np.array([[0,0.01,0],[0.01,0.3,0.01],[0.3,1.0,0.3]])
        self.punishment=-1.0
        
        
    def get_observation(self,st,action):
        state=[[np.argmax(st[0][0:3]),np.argmax(st[0][3:])]]
        next_state=np.zeros((no_of_actions,1,state_dim))
        #print(next_state.shape)
        reward=np.empty((1,no_of_actions))
        #print(next_state.shape)
        #print(state[0][0],(int)(state[0][1]))
#       print(self.grid[state[0][0]][state[0][1]+1])
        if (state[0][1]>0):
            ind=[state[0][0],state[0][1]-1+3]
            next_state[0][0][ind]=1
            reward[0][0]=self.grid[state[0][0]][state[0][1]-1]
        else: 
            next_state[0]=st
            reward[0][0]=self.punishment
        if (state[0][1]<2):
            ind=[state[0][0],state[0][1]+1+3]
            print(next_state.shape)
            next_state[1][0][ind]=1
            reward[0][1]=self.grid[state[0][0]][state[0][1]+1]
        else: 
            next_state[1]=st
            reward[0][1]=self.punishment
        if (state[0][0]>0):
            ind=[state[0][0]-1,state[0][1]+3]
            next_state[2][0][ind]=1
            reward[0][2]=self.grid[state[0][0]-1][state[0][1]]
        else: 
            next_state[2]=st
            reward[0][2]=self.punishment
        if(state[0][0]<2):
            ind=[state[0][0]+1,state[0][1]+3]
            next_state[3][0][ind]=1
            reward[0][3]=self.grid[state[0][0]+1][state[0][1]]        
        else: 
            next_state[3]=st
            reward[0][3]=self.punishment
            
        
            
        return (next_state,reward)
        

In [435]:
class Grid:
    def __init__(self):
        self.grid=np.array([[0,3,0],[3,50,3],[50,1000,50]])
        
        
    def get_observation(self,st,action):
        state=[[np.argmax(st[0][0:3]),np.argmax(st[0][3:])]]
        next_state=np.zeros((1,state_dim))
        #print(state[0][0],(int)(state[0][1]))
#       print(self.grid[state[0][0]][state[0][1]+1])
        if (action==0 and state[0][1]>0):
            ind=[state[0][0],state[0][1]-1+3]
            next_state[0][ind]=1
            reward=self.grid[state[0][0]][state[0][1]-1]
        elif (action==1 and state[0][1]<2):
            ind=[state[0][0],state[0][1]+1+3]
            next_state[0][ind]=1
            reward=self.grid[state[0][0]][state[0][1]+1]
        elif (action==2 and state[0][0]>0):
            ind=[state[0][0]-1,state[0][1]+3]
            next_state[0][ind]=1
            reward=self.grid[state[0][0]-1][state[0][1]]
        elif (action==3 and state[0][0]<2):
            ind=[state[0][0]+1,state[0][1]+3]
            next_state[0][ind]=1
            reward=self.grid[state[0][0]+1][state[0][1]]        
        else: 
            next_state=st
            reward=-1000
            
        return (next_state,reward)
        

In [421]:
next_state=np.zeros((no_of_actions,1,state_dim))
ind=[2,4,4]
next_state[3][0][ind]

array([0., 0., 0.])

In [440]:
def getModel():
    model=tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(3,input_shape=(state_dim,),activation='sigmoid'))
    model.add(tf.keras.layers.Dense(no_of_actions,activation='relu'))
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),loss='mse')
    return model

def get_action(state):
    actions=model.predict(state)
    #print(actions)
    a=np.array(np.random.choice([np.argmax(actions,1)[0],np.random.randint(3)],p=[eps,1-eps]))
    return a

In [442]:
model=getModel()
target_model=getModel()
target_model.set_weights(model.get_weights()) 


In [448]:
state=np.zeros((1,state_dim))
ind=[0,3]
state[0][ind]=1
print(state)
env=Grid()

for i in range(1000):
    eps=i/1000
    action=get_action(state)
    (next_state,reward)=env.get_observation(state,action)
    #print(state,next_state[action],reward[0][action],action)
    #print(reward.shape,target_model.predict(state).shape)
    target=reward+gama*np.max(target_model.predict(state),1)
    #print(target)
    model.fit(state,target,epochs=100)
    eps=i/1000
    print("target=",target_model.get_weights())
    target_model.set_weights(model.get_weights()) 
    print("model=",model.get_weights())
    print("target=",target_model.get_weights())
    input()
    state=next_state[action]


[[1. 0. 0. 1. 0. 0.]]
(4, 1, 6)
Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5001
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5001
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5001
Epoch 4/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5001
Epoch 5/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5001
Epoch 6/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5001
Epoch 7/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5001
Epoch 8/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5001
Epoch 9/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5001
Epoch 10/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5001
Epoch 11/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5001
Epoch 12/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5001
Epoch 13/100
1/1 [===========

KeyboardInterrupt: 

In [ ]:
state=np.zeros((1,state_dim))
ind=[0,3]
state[0][ind]=1
print(state)
env=Grid()

for i in range(1000):
    eps=i/1000
    action=get_action(state)
    (next_state,reward)=env.get_observation(state,action)
    #print(state,next_state[action],reward[0][action],action)
    #print(reward.shape,target_model.predict(state).shape)
    target=reward+gama*np.max(target_model.predict(state),1)
    #print(target)
    model.fit(state,target,epochs=100)
    eps=i/1000
    print("target=",target_model.get_weights())
    target_model.set_weights(model.get_weights()) 
    print("model=",model.get_weights())
    print("target=",target_model.get_weights())
    input()
    state=next_state[action]


In [402]:
state=np.zeros((1,state_dim))
ind=[0,3]
state[0][ind]=1
eps=1
count=0
for i in range(1000):
    
    action=get_action(state)
    (next_state,reward)=env.get_observation(state,action)
    print(state,next_state,action,reward)
    count=count+1
    if(reward==1000):
        break
    state=next_state
    
print(count)
    

[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1. 0. 0.]] [[1. 0. 0. 1. 0. 0.]] 0 -1000
[[1. 0. 0. 1

In [195]:
model.predict([[0.231,0.8]])

array([[0.97012424, 0.9708746 , 0.96857667]], dtype=float32)

In [3]:
y_true = [[0., 1.], [0., 0.]]
y_pred = [[1., 1.], [1., 0.]]
# Using 'auto'/'sum_over_batch_size' reduction type.
mse = tf.keras.losses.MeanSquaredError()
mse(y_true, y_pred).numpy()

0.5

In [26]:
target_model.set_weights(model.get_weights()) 

In [10]:
model.summary()

ValueError: This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build.

In [ ]:
opt = tf.keras.optimizers.SGD(learning_rate=0.1)
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(10, activation='relu'))
model.add(tf.keras.layers.Dense(10, activation='sigmoid'))
loss_fn = lambda: tf.keras.losses.mse(model(input), output)
var_list_fn = lambda: model.trainable_weights
with tf.GradientTape() as g:
    opt.minimize(loss_fn, var_list_fn)