In [3]:
import numpy as np

In [17]:
(i,j,k)=np.fromfunction(lambda i,j,k:(i,j,k),(5,5,3),dtype=int)

In [ ]:
np.fromfunction

In [18]:
(i,j,k)

(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],
 
        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],
 
        [[4, 4, 4],
         [4, 4, 4],
         [4, 4, 4],
         [4, 4, 4],
         [4, 4, 4]]]), array([[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4]],
 
        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4]],
 
        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4]],
 
        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4]],
 
        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2],
         [3, 3

In [15]:
a[i,j]

array([[ 0.96810387,  0.07928712,  0.25518639],
       [ 0.63097082,  0.34383082,  0.63870599],
       [ 0.49316021,  0.41321383,  0.87203367]])

In [31]:
x=np.random.rand(100,28,28,3)
k=np.random.rand(5,5,3,20)

In [22]:
x[i,j,k]

array([[[ 0.29294207,  0.40102423,  0.3475025 ],
        [ 0.36917905,  0.13807989,  0.81897947],
        [ 0.76102462,  0.42475807,  0.64667883],
        [ 0.45512312,  0.1195067 ,  0.27529901],
        [ 0.82744345,  0.46279551,  0.48793642]],

       [[ 0.31405152,  0.68188569,  0.85628292],
        [ 0.39359059,  0.43742647,  0.20572969],
        [ 0.67105749,  0.97813837,  0.74469979],
        [ 0.56520631,  0.44409647,  0.22569353],
        [ 0.05518293,  0.87054068,  0.57088281]],

       [[ 0.49371251,  0.94426594,  0.52545119],
        [ 0.9261558 ,  0.77644012,  0.09951468],
        [ 0.86787643,  0.58829543,  0.25183367],
        [ 0.52633277,  0.82292905,  0.18905369],
        [ 0.28457974,  0.34325644,  0.10098501]],

       [[ 0.0795227 ,  0.54756716,  0.89647346],
        [ 0.88359641,  0.9671301 ,  0.64829136],
        [ 0.19169614,  0.71682503,  0.44561084],
        [ 0.70698741,  0.27647237,  0.34332882],
        [ 0.48893305,  0.72053973,  0.96070936]],

       [[ 0.

In [23]:
x

array([[[ 0.29294207,  0.40102423,  0.3475025 ],
        [ 0.36917905,  0.13807989,  0.81897947],
        [ 0.76102462,  0.42475807,  0.64667883],
        ..., 
        [ 0.91396402,  0.07080246,  0.25636237],
        [ 0.27258694,  0.3404704 ,  0.7196969 ],
        [ 0.82702378,  0.18853428,  0.70071456]],

       [[ 0.31405152,  0.68188569,  0.85628292],
        [ 0.39359059,  0.43742647,  0.20572969],
        [ 0.67105749,  0.97813837,  0.74469979],
        ..., 
        [ 0.93419865,  0.83102536,  0.03059269],
        [ 0.85311291,  0.90845679,  0.98831989],
        [ 0.80843037,  0.17216443,  0.37011164]],

       [[ 0.49371251,  0.94426594,  0.52545119],
        [ 0.9261558 ,  0.77644012,  0.09951468],
        [ 0.86787643,  0.58829543,  0.25183367],
        ..., 
        [ 0.09601689,  0.84862814,  0.83641861],
        [ 0.08441372,  0.53279819,  0.36149366],
        [ 0.68693656,  0.27723001,  0.1200954 ]],

       ..., 
       [[ 0.48360313,  0.08614642,  0.33004821],
        

In [25]:
x[i,j+1,k]

array([[[ 0.36917905,  0.13807989,  0.81897947],
        [ 0.76102462,  0.42475807,  0.64667883],
        [ 0.45512312,  0.1195067 ,  0.27529901],
        [ 0.82744345,  0.46279551,  0.48793642],
        [ 0.78194519,  0.92276606,  0.47879164]],

       [[ 0.39359059,  0.43742647,  0.20572969],
        [ 0.67105749,  0.97813837,  0.74469979],
        [ 0.56520631,  0.44409647,  0.22569353],
        [ 0.05518293,  0.87054068,  0.57088281],
        [ 0.74738227,  0.70210693,  0.26253235]],

       [[ 0.9261558 ,  0.77644012,  0.09951468],
        [ 0.86787643,  0.58829543,  0.25183367],
        [ 0.52633277,  0.82292905,  0.18905369],
        [ 0.28457974,  0.34325644,  0.10098501],
        [ 0.29437147,  0.46260294,  0.01483378]],

       [[ 0.88359641,  0.9671301 ,  0.64829136],
        [ 0.19169614,  0.71682503,  0.44561084],
        [ 0.70698741,  0.27647237,  0.34332882],
        [ 0.48893305,  0.72053973,  0.96070936],
        [ 0.6963195 ,  0.92607745,  0.84011619]],

       [[ 0.

In [30]:
p=[]
q=[]
r=[]
for m in range(x.shape[1]-5+1):
    for n in range(x.shape[2]-5+1):
        (i,j,k)=np.fromfunction(lambda i,j,k:(i+m,j+n,k),(5,5,3),dtype=int)
        p.append(i)
        q.append(j)
        r.append(k)
x[:,p,q,r].shape        
        

(100, 576, 5, 5, 3)

In [34]:
tmp1=x[:,p,q,r].reshape(100*576,5*5*3)
tmp2=k.reshape(5*5*3,20)
img=np.dot(tmp1,tmp2)
img=img.reshape(100,24,24,20)

In [38]:
print(x.shape,k.shape,img.shape)


(100, 28, 28, 3) (5, 5, 3, 20) (100, 24, 24, 20)
